#!/usr/bin/env pwsh

#
# analyze-project.ps1 - AI-driven project analysis and modernization
#
# Usage:
#   ./analyze-project.ps1 PATH [-Output DIR]
#   ./analyze-project.ps1 -Project PATH [-Output DIR]
#
# This script enumerates a legacy project and prepares it for AI analysis.
# The AI agent will handle technology detection, file selection, and analysis.
#

[CmdletBinding()]
param(
    [Parameter(Mandatory=$false, Position=0)]
    [string]$Project = ".",

    [Parameter(Mandatory=$false, Position=1)]
    [string]$Output = "",

    [switch]$Help
)

$ErrorActionPreference = 'Stop'

# Script directory
$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$repoRoot = (Resolve-Path (Join-Path $scriptDir "../..")).Path

# Show help if requested
if ($Help) {
    Write-Output "Usage: $($MyInvocation.MyCommand.Name) PATH [-Output DIR]"
    Write-Output "       $($MyInvocation.MyCommand.Name) -Project PATH [-Output DIR]"
    Write-Output ""
    Write-Output "AI-driven analysis of legacy projects for reverse engineering and modernization."
    Write-Output ""
    Write-Output "Parameters:"
    Write-Output "  PATH (positional)    Path to project root directory (default: current directory)"
    Write-Output "  -Project PATH        Named parameter for project path"
    Write-Output "  -Output DIR         Output directory (default: .analysis/PROJECT_NAME-TIMESTAMP)"
    Write-Output "  -Help               Show this help message"
    Write-Output ""
    Write-Output "Examples:"
    Write-Output "  # Analyze current directory"
    Write-Output "  .\$($MyInvocation.MyCommand.Name) ."
    Write-Output ""
    Write-Output "  # Analyze specific project (positional)"
    Write-Output "  .\$($MyInvocation.MyCommand.Name) C:\path\to\project"
    Write-Output ""
    Write-Output "  # Analyze specific project (named parameter)"
    Write-Output "  .\$($MyInvocation.MyCommand.Name) -Project C:\path\to\project"
    Write-Output ""
    Write-Output "  # Custom output directory"
    Write-Output "  .\$($MyInvocation.MyCommand.Name) C:\path\to\project -Output C:\analysis-results"
    Write-Output ""
    Write-Output "Workflow:"
    Write-Output "  1. Enumerate all files in the project (full recursive scan)"
    Write-Output "  2. Generate file manifest with metadata (JSON)"
    Write-Output "  3. AI agent analyzes manifest and determines:"
    Write-Output "     - Technology stack and framework"
    Write-Output "     - Files to include/exclude (no hardcoded filters)"
    Write-Output "     - File reading strategy (full/sampled/metadata-only)"
    Write-Output "  4. AI agent reads selected files and generates comprehensive analysis"
    Write-Output ""
    Write-Output "Output:"
    Write-Output "  The script prepares an analysis workspace for AI with:"
    Write-Output "  - file-manifest.json    Complete file inventory with metadata"
    Write-Output "  - analysis-report.md    AI-generated comprehensive analysis"
    Write-Output "  - (Additional reports generated by AI as needed)"
    Write-Output ""
    exit 0
}

# Validate project path
if (-not (Test-Path $Project -PathType Container)) {
    Write-Error "ERROR: Project path does not exist or is not a directory: $Project"
    exit 1
}

$Project = (Resolve-Path $Project).Path
$projectName = Split-Path -Leaf $Project

Write-Host "`n====================================== " -ForegroundColor Blue
Write-Host "AI-Driven Project Analysis" -ForegroundColor Blue
Write-Host "====================================== `n" -ForegroundColor Blue

# Setup output directory
Write-Host "====================================== " -ForegroundColor Blue
Write-Host "Setting Up Analysis Workspace" -ForegroundColor Blue
Write-Host "====================================== " -ForegroundColor Blue

if ($Output -eq "") {
    $timestamp = Get-Date -Format "yyyy-MM-dd-HHmmss"
    $Output = Join-Path $Project ".analysis\$projectName-$timestamp"
}

New-Item -ItemType Directory -Path $Output -Force | Out-Null
New-Item -ItemType Directory -Path (Join-Path $Output "checkpoints") -Force | Out-Null
Write-Host "[OK] Output directory: $Output" -ForegroundColor Green

# Define output file paths (for AI agent reference)
$analysisReport = Join-Path $Output "analysis-report.md"
$recommendedSpec = Join-Path $Output "recommended-spec.md"
$dependencyAudit = Join-Path $Output "dependency-audit.json"
$metricsSummary = Join-Path $Output "metrics-summary.json"
$decisionMatrix = Join-Path $Output "decision-matrix.md"

Write-Host ""

# Run enumeration
Write-Host "====================================== " -ForegroundColor Blue
Write-Host "Enumerating Project Files" -ForegroundColor Blue
Write-Host "====================================== " -ForegroundColor Blue

Write-Host "[INFO] Running full recursive scan..." -ForegroundColor Blue
Write-Host "[INFO] AI will determine which files to analyze based on detected technology" -ForegroundColor Blue

$manifestFile = Join-Path $Output "file-manifest.json"
$enumerateScript = Join-Path $scriptDir "enumerate-project.ps1"

try {
    & $enumerateScript -Project $Project -Output $manifestFile -MaxSize 10485760
    Write-Host "[OK] File manifest generated: $manifestFile" -ForegroundColor Green

    # Display summary
    if (Test-Path $manifestFile) {
        $manifest = Get-Content $manifestFile | ConvertFrom-Json
        $totalFiles = $manifest.statistics.total_files
        $totalSizeMB = [math]::Round($manifest.statistics.total_size_bytes / 1MB, 2)

        Write-Host "[INFO] Total files: $totalFiles" -ForegroundColor Blue
        Write-Host "[INFO] Total size: ${totalSizeMB}MB" -ForegroundColor Blue
    }
}
catch {
    Write-Host "[X] File enumeration failed: $_" -ForegroundColor Red
    exit 1
}

Write-Host ""

# Create analysis workspace
Write-Host "====================================== " -ForegroundColor Blue
Write-Host "Preparing Analysis Workspace" -ForegroundColor Blue
Write-Host "====================================== " -ForegroundColor Blue

$analysisTemplate = @"
# Project Analysis Report

**Status**: Pending AI Analysis

**Project**: <!-- AI will fill this -->
**Analysis Date**: <!-- AI will fill this -->

---

## Instructions for AI Agent

This workspace has been prepared for comprehensive project analysis. Please:

1. **Read the file-manifest.json** to understand project structure
2. **Detect technology stack** from indicator files (package.json, *.csproj, etc.)
3. **Generate inclusion/exclusion rules** based on detected technology
   - Example: .NET projects exclude bin/, obj/, packages/
   - Example: Node.js projects exclude node_modules/, dist/, build/
4. **Categorize files by priority**:
   - Critical: package files, entry points, configs
   - Important: main source code
   - Supporting: tests, docs, scripts
5. **Read files based on priority and size**:
   - Full read: <100KB or critical files
   - Sampled: 100KB-1MB (first + last portions)
   - Metadata only: >1MB or binary files
6. **Generate comprehensive analysis** including:
   - Technology stack and versions
   - Project structure and architecture
   - Dependencies and their health
   - Code quality indicators
   - Modernization recommendations
   - Feasibility assessment (inline upgrade vs greenfield rewrite)

---

## Analysis Output

<!-- AI agent will replace this entire file with comprehensive analysis -->

"@

$analysisTemplate | Out-File -FilePath $analysisReport -Encoding utf8

Write-Host "[OK] Created analysis workspace" -ForegroundColor Green
Write-Host "[INFO] Analysis report template: $analysisReport" -ForegroundColor Blue
Write-Host "[INFO] Additional artifacts will be generated by AI:" -ForegroundColor Blue
Write-Host "[INFO]   - $recommendedSpec" -ForegroundColor Blue
Write-Host "[INFO]   - $dependencyAudit" -ForegroundColor Blue
Write-Host "[INFO]   - $metricsSummary" -ForegroundColor Blue
Write-Host "[INFO]   - $decisionMatrix" -ForegroundColor Blue
Write-Host ""

# Show summary
Write-Host "====================================== " -ForegroundColor Blue
Write-Host "Analysis Workspace Ready" -ForegroundColor Blue
Write-Host "====================================== " -ForegroundColor Blue

Write-Host "[OK] Workspace created successfully!" -ForegroundColor Green
Write-Host ""
Write-Host "[INFO] Workspace location: $Output" -ForegroundColor Blue
Write-Host "[INFO] File manifest: $manifestFile" -ForegroundColor Blue
Write-Host ""
Write-Host "[INFO] Next steps:" -ForegroundColor Blue
Write-Host "[INFO] 1. AI agent will analyze the file manifest" -ForegroundColor Blue
Write-Host "[INFO] 2. AI will detect technology and generate filter rules" -ForegroundColor Blue
Write-Host "[INFO] 3. AI will read relevant files and generate comprehensive analysis" -ForegroundColor Blue
Write-Host "[INFO] 4. Results will be saved to analysis-report.md" -ForegroundColor Blue
Write-Host ""
Write-Host "[OK] [AI] Ready for AI analysis!" -ForegroundColor Green
