#!/usr/bin/env pwsh

#
# generate-guidelines.ps1 - Corporate guideline generation from documents and reference projects
#
# Usage:
#   ./generate-guidelines.ps1 PATH
#   ./generate-guidelines.ps1 -Sources PATH
#
# This script enumerates corporate documents and reference projects for AI analysis.
# The AI agent will extract principles and generate/update coding guidelines.
#

[CmdletBinding()]
param(
    [Parameter(Mandatory=$false, Position=0)]
    [string]$Sources = "",

    [switch]$Help
)

$ErrorActionPreference = 'Stop'

# Script directory
$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$repoRoot = (Resolve-Path (Join-Path $scriptDir "../..")).Path

# Output directory (fixed location)
$outputDir = Join-Path $repoRoot ".guidelines-analysis"

# Show help if requested
if ($Help -or $Sources -eq "") {
    Write-Output @"
Usage: $($MyInvocation.MyCommand.Name) PATH
       $($MyInvocation.MyCommand.Name) -Sources PATH

Generate or update corporate coding guidelines from documents and reference projects.

Parameters:
  PATH (positional)    Path to folder containing docs/ and reference-projects/ subdirectories
  -Sources PATH        Named parameter for sources path
  -Help                Show this help message

Expected structure:
  SOURCES_PATH\
    ├── docs\
    │   ├── security-guidelines.pdf
    │   ├── coding-standards.md
    │   └── ...
    └── reference-projects\
        ├── project-a\
        ├── project-b\
        └── ...

Examples:
  # Generate guidelines from temp folder
  .\$($MyInvocation.MyCommand.Name) C:\temp\my-standards

  # Generate guidelines with named parameter
  .\$($MyInvocation.MyCommand.Name) -Sources C:\temp\my-standards

Workflow:
  1. Enumerate all documents in docs\ subdirectory
  2. Enumerate all reference projects in reference-projects\ subdirectory
  3. Generate file manifests (JSON)
  4. Create analysis workspace (.guidelines-analysis\)
  5. AI agent analyzes:
     - Documents: Extract explicit principles
     - Code: Reverse-engineer implicit patterns
     - Synthesize: Merge findings into guidelines

Output:
  The script prepares an analysis workspace for AI with:
  - documents-manifest.json      List of corporate documents
  - projects-manifest.json       List of reference projects
  - {project-name}-files.json    File inventory per project
  - (Guidelines generated by AI in .guidelines\ directory)

"@
    exit 0
}

# Validate sources path
if (-not (Test-Path $Sources -PathType Container)) {
    Write-Host "`n✗ ERROR: Sources path does not exist or is not a directory: $Sources" -ForegroundColor Red
    exit 1
}

$Sources = (Resolve-Path $Sources).Path

# Welcome message
Write-Host "`n====================================== " -ForegroundColor Blue
Write-Host "Corporate Guideline Generation" -ForegroundColor Blue
Write-Host "====================================== `n" -ForegroundColor Blue

# Validate sources path (detailed)
Write-Host "====================================== " -ForegroundColor Blue
Write-Host "Validating Sources Path" -ForegroundColor Blue
Write-Host "====================================== " -ForegroundColor Blue
Write-Host "✓ Sources path: $Sources" -ForegroundColor Green
Write-Host ""

# Check structure
Write-Host "====================================== " -ForegroundColor Blue
Write-Host "Checking Directory Structure" -ForegroundColor Blue
Write-Host "====================================== " -ForegroundColor Blue

$hasDocs = Test-Path (Join-Path $Sources "docs") -PathType Container
$hasProjects = Test-Path (Join-Path $Sources "reference-projects") -PathType Container

if ($hasDocs) {
    Write-Host "✓ Found docs\ subdirectory" -ForegroundColor Green
} else {
    Write-Host "⚠ docs\ subdirectory not found" -ForegroundColor Yellow
    Write-Host "ℹ Looking for documents in root..." -ForegroundColor Blue
}

if ($hasProjects) {
    Write-Host "✓ Found reference-projects\ subdirectory" -ForegroundColor Green
} else {
    Write-Host "⚠ reference-projects\ subdirectory not found" -ForegroundColor Yellow
    Write-Host "ℹ Looking for projects in root..." -ForegroundColor Blue
}

if (-not $hasDocs -and -not $hasProjects) {
    Write-Host "⚠ Expected structure not found, but continuing..." -ForegroundColor Yellow
    Write-Host "ℹ AI will attempt to categorize files automatically" -ForegroundColor Blue
}

Write-Host ""

# Setup output directory
Write-Host "====================================== " -ForegroundColor Blue
Write-Host "Setting Up Analysis Workspace" -ForegroundColor Blue
Write-Host "====================================== " -ForegroundColor Blue

New-Item -ItemType Directory -Path $outputDir -Force | Out-Null
Write-Host "✓ Output directory: $outputDir" -ForegroundColor Green
Write-Host ""

# Enumerate documents
Write-Host "====================================== " -ForegroundColor Blue
Write-Host "Enumerating Corporate Documents" -ForegroundColor Blue
Write-Host "====================================== " -ForegroundColor Blue

$docsDir = if ($hasDocs) { Join-Path $Sources "docs" } else { $Sources }
Write-Host "ℹ Scanning for documents (*.pdf, *.md, *.docx, *.txt)..." -ForegroundColor Blue

$docFiles = Get-ChildItem -Path $docsDir -Recurse -File -Include @("*.pdf", "*.md", "*.docx", "*.txt", "*.doc") -ErrorAction SilentlyContinue

$documentsManifest = Join-Path $outputDir "documents-manifest.json"

if ($docFiles.Count -eq 0) {
    Write-Host "⚠ No documents found in $docsDir" -ForegroundColor Yellow
    @{
        documents = @()
        count = 0
        base_path = $docsDir
    } | ConvertTo-Json -Depth 10 | Set-Content $documentsManifest
} else {
    $documents = @()
    foreach ($doc in $docFiles) {
        $relPath = $doc.FullName.Substring($docsDir.Length + 1)
        $documents += @{
            path = $doc.FullName
            relative_path = $relPath
            filename = $doc.Name
            size_bytes = $doc.Length
        }
    }

    @{
        documents = $documents
        count = $docFiles.Count
        base_path = $docsDir
    } | ConvertTo-Json -Depth 10 | Set-Content $documentsManifest

    Write-Host "✓ Found $($docFiles.Count) documents" -ForegroundColor Green
    Write-Host "✓ Manifest: $documentsManifest" -ForegroundColor Green
}

Write-Host ""

# Enumerate projects
Write-Host "====================================== " -ForegroundColor Blue
Write-Host "Enumerating Reference Projects" -ForegroundColor Blue
Write-Host "====================================== " -ForegroundColor Blue

$projectsDir = if ($hasProjects) { Join-Path $Sources "reference-projects" } else { $Sources }
Write-Host "ℹ Scanning for reference projects..." -ForegroundColor Blue

$projectDirs = Get-ChildItem -Path $projectsDir -Directory -ErrorAction SilentlyContinue | Where-Object {
    $_.Name -notmatch '^\.' -and
    $_.Name -ne 'docs' -and
    $_.Name -ne 'node_modules'
}

$projectsManifest = Join-Path $outputDir "projects-manifest.json"

if ($projectDirs.Count -eq 0) {
    Write-Host "⚠ No reference projects found in $projectsDir" -ForegroundColor Yellow
    @{
        projects = @()
        count = 0
        base_path = $projectsDir
    } | ConvertTo-Json -Depth 10 | Set-Content $projectsManifest
} else {
    $projects = @()
    foreach ($proj in $projectDirs) {
        $relPath = $proj.FullName.Substring($projectsDir.Length + 1)
        $fileCount = (Get-ChildItem -Path $proj.FullName -Recurse -File -ErrorAction SilentlyContinue).Count

        $projects += @{
            path = $proj.FullName
            relative_path = $relPath
            name = $proj.Name
            file_count = $fileCount
        }

        # Enumerate files in this project
        Write-Host "ℹ   Enumerating files in $($proj.Name)..." -ForegroundColor Blue

        $projectFilesManifest = Join-Path $outputDir "$($proj.Name)-files.json"

        $projectFiles = Get-ChildItem -Path $proj.FullName -Recurse -File -ErrorAction SilentlyContinue | Where-Object {
            $_.FullName -notmatch '[\\/](node_modules|bin|obj|target|build|dist|\.git|__pycache__|venv|\.venv)($|[\\/])' -and
            $_.Length -le 10MB
        }

        $files = @()
        foreach ($file in $projectFiles) {
            $relFilePath = $file.FullName.Substring($proj.FullName.Length + 1)
            $files += @{
                path = $file.FullName
                relative_path = $relFilePath
                filename = $file.Name
                size_bytes = $file.Length
                extension = $file.Extension
            }
        }

        @{
            project_name = $proj.Name
            project_path = $proj.FullName
            files = $files
            file_count = $files.Count
        } | ConvertTo-Json -Depth 10 | Set-Content $projectFilesManifest

        Write-Host "✓     Enumerated $($files.Count) files -> $($proj.Name)-files.json" -ForegroundColor Green
    }

    @{
        projects = $projects
        count = $projectDirs.Count
        base_path = $projectsDir
    } | ConvertTo-Json -Depth 10 | Set-Content $projectsManifest

    Write-Host "✓ Found $($projectDirs.Count) reference projects" -ForegroundColor Green
    Write-Host "✓ Manifest: $projectsManifest" -ForegroundColor Green
}

Write-Host ""

# Show summary
Write-Host "====================================== " -ForegroundColor Blue
Write-Host "Analysis Workspace Ready" -ForegroundColor Blue
Write-Host "====================================== " -ForegroundColor Blue

Write-Host "✓ Workspace created successfully!" -ForegroundColor Green
Write-Host ""
Write-Host "ℹ Workspace location: $outputDir" -ForegroundColor Blue
Write-Host "ℹ Documents manifest: $documentsManifest" -ForegroundColor Blue
Write-Host "ℹ Projects manifest: $projectsManifest" -ForegroundColor Blue
Write-Host ""

# Read counts from manifests
$docCount = if (Test-Path $documentsManifest) {
    $docManifest = Get-Content $documentsManifest | ConvertFrom-Json
    $docManifest.count
} else { 0 }

$projCount = if (Test-Path $projectsManifest) {
    $projManifest = Get-Content $projectsManifest | ConvertFrom-Json
    $projManifest.count
} else { 0 }

Write-Host "ℹ Summary:" -ForegroundColor Blue
Write-Host "ℹ   - Corporate documents: $docCount" -ForegroundColor Blue
Write-Host "ℹ   - Reference projects: $projCount" -ForegroundColor Blue
Write-Host ""

if ($docCount -eq 0 -and $projCount -eq 0) {
    Write-Host "✗ No documents or projects found!" -ForegroundColor Red
    Write-Host "ℹ Expected structure:" -ForegroundColor Blue
    Write-Host "ℹ   $Sources\docs\           (corporate documents)" -ForegroundColor Blue
    Write-Host "ℹ   $Sources\reference-projects\  (reference codebases)" -ForegroundColor Blue
    exit 1
}

if ($docCount -eq 0) {
    Write-Host "⚠ No corporate documents found" -ForegroundColor Yellow
    Write-Host "ℹ Guidelines will be generated from reference projects only" -ForegroundColor Blue
}

if ($projCount -eq 0) {
    Write-Host "⚠ No reference projects found" -ForegroundColor Yellow
    Write-Host "ℹ Guidelines will be generated from documents only" -ForegroundColor Blue
}

Write-Host ""
Write-Host "ℹ Next steps:" -ForegroundColor Blue
Write-Host "ℹ 1. AI will analyze documents to extract explicit principles" -ForegroundColor Blue
Write-Host "ℹ 2. AI will analyze reference projects to identify implicit patterns" -ForegroundColor Blue
Write-Host "ℹ 3. AI will synthesize findings into coding guidelines" -ForegroundColor Blue
Write-Host "ℹ 4. Generated guidelines will be saved to .guidelines\ directory" -ForegroundColor Blue
Write-Host ""
Write-Host "✓ 🤖 Ready for AI analysis!" -ForegroundColor Green
