#!/usr/bin/env pwsh

#
# generate-guidelines.ps1 - Corporate guideline generation from documents and reference projects
#
# Usage:
#   ./generate-guidelines.ps1 PATH
#   ./generate-guidelines.ps1 -Sources PATH
#
# This script enumerates corporate documents and reference projects for AI analysis.
# The AI agent will extract principles and generate/update coding guidelines.
#

[CmdletBinding()]
param(
    [Parameter(Mandatory=$false, Position=0)]
    [string]$Sources = "",

    [switch]$Help
)

$ErrorActionPreference = 'Stop'

# Script directory
$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$repoRoot = (Resolve-Path (Join-Path $scriptDir "../..")).Path

# Load common functions and detect OS
. (Join-Path $scriptDir "common.ps1")
$OS = Get-DetectedOS

# If Unix detected, redirect to bash script
if ($OS -eq "unix") {
    $bashScript = Join-Path $scriptDir "../bash/generate-guidelines.sh"
    $bashArgs = @()

    # Convert PowerShell parameters to bash arguments
    if ($Sources) { $bashArgs += $Sources }
    if ($Help) { $bashArgs += "--help" }

    & bash $bashScript @bashArgs
    exit $LASTEXITCODE
}

# Output directory (fixed location)
$outputDir = Join-Path $repoRoot ".guidelines-analysis"

# Show help if requested
if ($Help -or $Sources -eq "") {
    Write-Output "Usage: $($MyInvocation.MyCommand.Name) PATH"
    Write-Output "       $($MyInvocation.MyCommand.Name) -Sources PATH"
    Write-Output ""
    Write-Output "Generate or update corporate coding guidelines from documents and reference projects."
    Write-Output ""
    Write-Output "Parameters:"
    Write-Output "  PATH (positional)    Path to folder containing docs/ and reference-projects/ subdirectories"
    Write-Output "  -Sources PATH        Named parameter for sources path"
    Write-Output "  -Help                Show this help message"
    Write-Output ""
    Write-Output "Expected structure:"
    Write-Output "  SOURCES_PATH\"
    Write-Output "    +-- docs\"
    Write-Output "    |   +-- security-guidelines.pdf"
    Write-Output "    |   +-- coding-standards.md"
    Write-Output "    |   +-- ..."
    Write-Output "    +-- reference-projects\"
    Write-Output "        +-- project-a\"
    Write-Output "        +-- project-b\"
    Write-Output "        +-- ..."
    Write-Output ""
    Write-Output "Examples:"
    Write-Output "  # Generate guidelines from temp folder"
    Write-Output "  .\$($MyInvocation.MyCommand.Name) C:\temp\my-standards"
    Write-Output ""
    Write-Output "  # Generate guidelines with named parameter"
    Write-Output "  .\$($MyInvocation.MyCommand.Name) -Sources C:\temp\my-standards"
    Write-Output ""
    Write-Output "Workflow:"
    Write-Output "  1. Enumerate all documents in docs\ subdirectory"
    Write-Output "  2. Enumerate all reference projects in reference-projects\ subdirectory"
    Write-Output "  3. Generate file manifests (JSON)"
    Write-Output "  4. Create analysis workspace (.guidelines-analysis\)"
    Write-Output "  5. AI agent analyzes:"
    Write-Output "     - Documents: Extract explicit principles"
    Write-Output "     - Code: Reverse-engineer implicit patterns"
    Write-Output "     - Synthesize: Merge findings into guidelines"
    Write-Output ""
    Write-Output "Output:"
    Write-Output "  The script prepares an analysis workspace for AI with:"
    Write-Output "  - documents-manifest.json      List of corporate documents"
    Write-Output "  - projects-manifest.json       List of reference projects"
    Write-Output "  - {project-name}-files.json    File inventory per project"
    Write-Output "  - (Guidelines generated by AI in .guidelines\ directory)"
    Write-Output ""
    exit 0
}

# Validate sources path
if (-not (Test-Path $Sources -PathType Container)) {
    Write-Host "`n[X] ERROR: Sources path does not exist or is not a directory: $Sources" -ForegroundColor Red
    exit 1
}

$Sources = (Resolve-Path $Sources).Path

# Welcome message
Write-Host "`n====================================== " -ForegroundColor Blue
Write-Host "Corporate Guideline Generation" -ForegroundColor Blue
Write-Host "====================================== `n" -ForegroundColor Blue

# Validate sources path (detailed)
Write-Host "====================================== " -ForegroundColor Blue
Write-Host "Validating Sources Path" -ForegroundColor Blue
Write-Host "====================================== " -ForegroundColor Blue
Write-Host "[OK] Sources path: $Sources" -ForegroundColor Green
Write-Host ""

# Check structure
Write-Host "====================================== " -ForegroundColor Blue
Write-Host "Checking Directory Structure" -ForegroundColor Blue
Write-Host "====================================== " -ForegroundColor Blue

$hasDocs = Test-Path (Join-Path $Sources "docs") -PathType Container
$hasProjects = Test-Path (Join-Path $Sources "reference-projects") -PathType Container

if ($hasDocs) {
    Write-Host "[OK] Found docs\ subdirectory" -ForegroundColor Green
} else {
    Write-Host "[WARNING] docs\ subdirectory not found" -ForegroundColor Yellow
    Write-Host "[INFO] Looking for documents in root..." -ForegroundColor Blue
}

if ($hasProjects) {
    Write-Host "[OK] Found reference-projects\ subdirectory" -ForegroundColor Green
} else {
    Write-Host "[WARNING] reference-projects\ subdirectory not found" -ForegroundColor Yellow
    Write-Host "[INFO] Looking for projects in root..." -ForegroundColor Blue
}

if (-not $hasDocs -and -not $hasProjects) {
    Write-Host "[WARNING] Expected structure not found, but continuing..." -ForegroundColor Yellow
    Write-Host "[INFO] AI will attempt to categorize files automatically" -ForegroundColor Blue
}

Write-Host ""

# Setup output directory
Write-Host "====================================== " -ForegroundColor Blue
Write-Host "Setting Up Analysis Workspace" -ForegroundColor Blue
Write-Host "====================================== " -ForegroundColor Blue

New-Item -ItemType Directory -Path $outputDir -Force | Out-Null
Write-Host "[OK] Output directory: $outputDir" -ForegroundColor Green
Write-Host ""

# Enumerate documents
Write-Host "====================================== " -ForegroundColor Blue
Write-Host "Enumerating Corporate Documents" -ForegroundColor Blue
Write-Host "====================================== " -ForegroundColor Blue

$docsDir = if ($hasDocs) { Join-Path $Sources "docs" } else { $Sources }
Write-Host "[INFO] Scanning for documents (*.pdf, *.md, *.docx, *.txt)..." -ForegroundColor Blue

$docFiles = Get-ChildItem -Path $docsDir -Recurse -File -Include @("*.pdf", "*.md", "*.docx", "*.txt", "*.doc") -ErrorAction SilentlyContinue

$documentsManifest = Join-Path $outputDir "documents-manifest.json"

if ($docFiles.Count -eq 0) {
    Write-Host "[WARNING] No documents found in $docsDir" -ForegroundColor Yellow
    @{
        documents = @()
        count = 0
        base_path = $docsDir
    } | ConvertTo-Json -Depth 10 | Set-Content $documentsManifest
} else {
    $documents = @()
    foreach ($doc in $docFiles) {
        $relPath = $doc.FullName.Substring($docsDir.Length + 1)
        $documents += @{
            path = $doc.FullName
            relative_path = $relPath
            filename = $doc.Name
            size_bytes = $doc.Length
        }
    }

    @{
        documents = $documents
        count = $docFiles.Count
        base_path = $docsDir
    } | ConvertTo-Json -Depth 10 | Set-Content $documentsManifest

    Write-Host "[OK] Found $($docFiles.Count) documents" -ForegroundColor Green
    Write-Host "[OK] Manifest: $documentsManifest" -ForegroundColor Green
}

Write-Host ""

# Enumerate projects
Write-Host "====================================== " -ForegroundColor Blue
Write-Host "Enumerating Reference Projects" -ForegroundColor Blue
Write-Host "====================================== " -ForegroundColor Blue

$projectsDir = if ($hasProjects) { Join-Path $Sources "reference-projects" } else { $Sources }
Write-Host "[INFO] Scanning for reference projects..." -ForegroundColor Blue

$projectDirs = Get-ChildItem -Path $projectsDir -Directory -ErrorAction SilentlyContinue | Where-Object {
    $_.Name -notmatch '^\.' -and
    $_.Name -ne 'docs' -and
    $_.Name -ne 'node_modules'
}

$projectsManifest = Join-Path $outputDir "projects-manifest.json"

if ($projectDirs.Count -eq 0) {
    Write-Host "[WARNING] No reference projects found in $projectsDir" -ForegroundColor Yellow
    @{
        projects = @()
        count = 0
        base_path = $projectsDir
    } | ConvertTo-Json -Depth 10 | Set-Content $projectsManifest
} else {
    $projects = @()
    foreach ($proj in $projectDirs) {
        $relPath = $proj.FullName.Substring($projectsDir.Length + 1)
        $fileCount = (Get-ChildItem -Path $proj.FullName -Recurse -File -ErrorAction SilentlyContinue).Count

        $projects += @{
            path = $proj.FullName
            relative_path = $relPath
            name = $proj.Name
            file_count = $fileCount
        }

        # Enumerate files in this project
        Write-Host "[INFO]   Enumerating files in $($proj.Name)..." -ForegroundColor Blue

        $projectFilesManifest = Join-Path $outputDir "$($proj.Name)-files.json"

        $projectFiles = Get-ChildItem -Path $proj.FullName -Recurse -File -ErrorAction SilentlyContinue | Where-Object {
            $_.FullName -notmatch '[\\/](node_modules|bin|obj|target|build|dist|\.git|__pycache__|venv|\.venv)($|[\\/])' -and
            $_.Length -le 10MB
        }

        $files = @()
        foreach ($file in $projectFiles) {
            $relFilePath = $file.FullName.Substring($proj.FullName.Length + 1)
            $files += @{
                path = $file.FullName
                relative_path = $relFilePath
                filename = $file.Name
                size_bytes = $file.Length
                extension = $file.Extension
            }
        }

        @{
            project_name = $proj.Name
            project_path = $proj.FullName
            files = $files
            file_count = $files.Count
        } | ConvertTo-Json -Depth 10 | Set-Content $projectFilesManifest

        Write-Host "[OK]     Enumerated $($files.Count) files -> $($proj.Name)-files.json" -ForegroundColor Green
    }

    @{
        projects = $projects
        count = $projectDirs.Count
        base_path = $projectsDir
    } | ConvertTo-Json -Depth 10 | Set-Content $projectsManifest

    Write-Host "[OK] Found $($projectDirs.Count) reference projects" -ForegroundColor Green
    Write-Host "[OK] Manifest: $projectsManifest" -ForegroundColor Green
}

Write-Host ""

# Show summary
Write-Host "====================================== " -ForegroundColor Blue
Write-Host "Analysis Workspace Ready" -ForegroundColor Blue
Write-Host "====================================== " -ForegroundColor Blue

Write-Host "[OK] Workspace created successfully!" -ForegroundColor Green
Write-Host ""
Write-Host "[INFO] Workspace location: $outputDir" -ForegroundColor Blue
Write-Host "[INFO] Documents manifest: $documentsManifest" -ForegroundColor Blue
Write-Host "[INFO] Projects manifest: $projectsManifest" -ForegroundColor Blue
Write-Host ""

# Read counts from manifests
$docCount = if (Test-Path $documentsManifest) {
    $docManifest = Get-Content $documentsManifest | ConvertFrom-Json
    $docManifest.count
} else { 0 }

$projCount = if (Test-Path $projectsManifest) {
    $projManifest = Get-Content $projectsManifest | ConvertFrom-Json
    $projManifest.count
} else { 0 }

Write-Host "[INFO] Summary:" -ForegroundColor Blue
Write-Host "[INFO]   - Corporate documents: $docCount" -ForegroundColor Blue
Write-Host "[INFO]   - Reference projects: $projCount" -ForegroundColor Blue
Write-Host ""

if ($docCount -eq 0 -and $projCount -eq 0) {
    Write-Host "[X] No documents or projects found!" -ForegroundColor Red
    Write-Host "[INFO] Expected structure:" -ForegroundColor Blue
    Write-Host "[INFO]   $Sources\docs\           (corporate documents)" -ForegroundColor Blue
    Write-Host "[INFO]   $Sources\reference-projects\  (reference codebases)" -ForegroundColor Blue
    exit 1
}

if ($docCount -eq 0) {
    Write-Host "[WARNING] No corporate documents found" -ForegroundColor Yellow
    Write-Host "[INFO] Guidelines will be generated from reference projects only" -ForegroundColor Blue
}

if ($projCount -eq 0) {
    Write-Host "[WARNING] No reference projects found" -ForegroundColor Yellow
    Write-Host "[INFO] Guidelines will be generated from documents only" -ForegroundColor Blue
}

Write-Host ""
Write-Host "[INFO] Next steps:" -ForegroundColor Blue
Write-Host "[INFO] 1. AI will analyze documents to extract explicit principles" -ForegroundColor Blue
Write-Host "[INFO] 2. AI will analyze reference projects to identify implicit patterns" -ForegroundColor Blue
Write-Host "[INFO] 3. AI will synthesize findings into coding guidelines" -ForegroundColor Blue
Write-Host "[INFO] 4. Generated guidelines will be saved to .guidelines\ directory" -ForegroundColor Blue
Write-Host ""
Write-Host "[OK] [AI] Ready for AI analysis!" -ForegroundColor Green
