#!/usr/bin/env bash

#
# analyze-project.sh - AI-driven project analysis and modernization
#
# Usage:
#   ./analyze-project.sh [PROJECT_PATH] [--output DIR]
#
# This script enumerates a legacy project and prepares it for AI analysis.
# The AI agent will handle technology detection, file selection, and analysis.
#

set -euo pipefail

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Default values
OUTPUT_DIR=""
PROJECT_PATH=""

# Script directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

# Functions

print_header() {
    echo -e "${BLUE}======================================${NC}"
    echo -e "${BLUE}$1${NC}"
    echo -e "${BLUE}======================================${NC}"
}

print_success() {
    echo -e "${GREEN}✓ $1${NC}"
}

print_error() {
    echo -e "${RED}✗ $1${NC}"
}

print_warning() {
    echo -e "${YELLOW}⚠ $1${NC}"
}

print_info() {
    echo -e "${BLUE}ℹ $1${NC}"
}

usage() {
    cat <<EOF
Usage: $0 [PROJECT_PATH] [--output DIR]

AI-driven analysis of legacy projects for reverse engineering and modernization.

Arguments:
  PROJECT_PATH         Path to project root directory (default: current directory)

Options:
  --output DIR         Output directory (default: .analysis/PROJECT_NAME-TIMESTAMP)
  -h, --help           Show this help message

Examples:
  # Analyze current directory
  $0 .

  # Analyze specific project
  $0 /path/to/project

  # Custom output directory
  $0 /path/to/project --output /tmp/analysis-results

Workflow:
  1. Enumerate all files in the project (full recursive scan)
  2. Generate file manifest with metadata (JSON)
  3. AI agent analyzes manifest and determines:
     - Technology stack and framework
     - Files to include/exclude (no hardcoded filters)
     - File reading strategy (full/sampled/metadata-only)
  4. AI agent reads selected files and generates comprehensive analysis

Output:
  The script prepares an analysis workspace for AI with:
  - file-manifest.json    Complete file inventory with metadata
  - analysis-report.md    AI-generated comprehensive analysis
  - (Additional reports generated by AI as needed)

EOF
    exit 0
}

check_dependencies() {
    print_header "Checking Dependencies"

    local missing=0

    # Check jq (required for enumerate-project.sh)
    if ! command -v jq &> /dev/null; then
        print_error "jq is required but not installed"
        print_info "Why? It prevents JSON injection vulnerabilities"
        print_info "Install: sudo apt-get install jq  OR  brew install jq"
        print_info "Corporate? Download portable binary: https://github.com/jqlang/jq/releases"
        print_info "Alternative: Use PowerShell version (scripts/powershell/analyze-project.ps1)"
        missing=1
    else
        print_success "jq found: $(jq --version)"
    fi

    if [[ $missing -eq 1 ]]; then
        exit 1
    fi

    echo ""
}

validate_project_path() {
    print_header "Validating Project Path"

    if [ ! -d "$PROJECT_PATH" ]; then
        print_error "Project path does not exist: $PROJECT_PATH"
        exit 1
    fi

    PROJECT_PATH="$(cd "$PROJECT_PATH" && pwd)"
    print_success "Project path: $PROJECT_PATH"

    # Detect project name
    PROJECT_NAME=$(basename "$PROJECT_PATH")
    print_success "Project name: $PROJECT_NAME"

    echo ""
}

setup_output_directory() {
    print_header "Setting Up Analysis Workspace"

    if [ -z "$OUTPUT_DIR" ]; then
        TIMESTAMP=$(date +%Y-%m-%d-%H%M%S)
        OUTPUT_DIR="$PROJECT_PATH/.analysis/$PROJECT_NAME-$TIMESTAMP"
    fi

    mkdir -p "$OUTPUT_DIR"
    mkdir -p "$OUTPUT_DIR/checkpoints"
    print_success "Output directory: $OUTPUT_DIR"

    # Define output file paths (for AI agent reference)
    ANALYSIS_REPORT="$OUTPUT_DIR/analysis-report.md"
    RECOMMENDED_SPEC="$OUTPUT_DIR/recommended-spec.md"
    DEPENDENCY_AUDIT="$OUTPUT_DIR/dependency-audit.json"
    METRICS_SUMMARY="$OUTPUT_DIR/metrics-summary.json"
    DECISION_MATRIX="$OUTPUT_DIR/decision-matrix.md"

    echo ""
}

run_enumeration() {
    print_header "Enumerating Project Files"

    print_info "Running full recursive scan..."
    print_info "AI will determine which files to analyze based on detected technology"

    # Run enumeration script
    local MANIFEST_FILE="$OUTPUT_DIR/file-manifest.json"

    if ! "$SCRIPT_DIR/enumerate-project.sh" \
        --project "$PROJECT_PATH" \
        --output "$MANIFEST_FILE" \
        --max-size 10485760; then
        print_error "File enumeration failed"
        exit 1
    fi

    print_success "File manifest generated: $MANIFEST_FILE"

    # Display summary
    if [ -f "$MANIFEST_FILE" ]; then
        local total_files=$(jq -r '.statistics.total_files' "$MANIFEST_FILE" 2>/dev/null || echo "unknown")
        local total_size=$(jq -r '.statistics.total_size_bytes' "$MANIFEST_FILE" 2>/dev/null || echo "0")
        local total_size_mb=$((total_size / 1024 / 1024))

        print_info "Total files: $total_files"
        print_info "Total size: ${total_size_mb}MB"
    fi

    echo ""
}

create_analysis_workspace() {
    print_header "Preparing Analysis Workspace"

    # Create placeholder for AI-generated analysis
    cat > "$ANALYSIS_REPORT" <<'EOF'
# Project Analysis Report

**Status**: Pending AI Analysis

**Project**: <!-- AI will fill this -->
**Analysis Date**: <!-- AI will fill this -->

---

## Instructions for AI Agent

This workspace has been prepared for comprehensive project analysis. Please:

1. **Read the file-manifest.json** to understand project structure
2. **Detect technology stack** from indicator files (package.json, *.csproj, etc.)
3. **Generate inclusion/exclusion rules** based on detected technology
   - Example: .NET projects exclude bin/, obj/, packages/
   - Example: Node.js projects exclude node_modules/, dist/, build/
4. **Categorize files by priority**:
   - Critical: package files, entry points, configs
   - Important: main source code
   - Supporting: tests, docs, scripts
5. **Read files based on priority and size**:
   - Full read: <100KB or critical files
   - Sampled: 100KB-1MB (first + last portions)
   - Metadata only: >1MB or binary files
6. **Generate comprehensive analysis** including:
   - Technology stack and versions
   - Project structure and architecture
   - Dependencies and their health
   - Code quality indicators
   - Modernization recommendations
   - Feasibility assessment (inline upgrade vs greenfield rewrite)

---

## Analysis Output

<!-- AI agent will replace this entire file with comprehensive analysis -->

EOF

    print_success "Created analysis workspace"
    print_info "Analysis report template: $ANALYSIS_REPORT"
    print_info "Additional artifacts will be generated by AI:"
    print_info "  - $RECOMMENDED_SPEC"
    print_info "  - $DEPENDENCY_AUDIT"
    print_info "  - $METRICS_SUMMARY"
    print_info "  - $DECISION_MATRIX"

    echo ""
}

show_summary() {
    print_header "Analysis Workspace Ready"

    print_success "Workspace created successfully!"
    echo ""
    print_info "Workspace location: $OUTPUT_DIR"
    print_info "File manifest: $OUTPUT_DIR/file-manifest.json"
    echo ""
    print_info "Next steps:"
    print_info "1. AI agent will analyze the file manifest"
    print_info "2. AI will detect technology and generate filter rules"
    print_info "3. AI will read relevant files and generate comprehensive analysis"
    print_info "4. Results will be saved to analysis-report.md"
    echo ""
    print_success "🤖 Ready for AI analysis!"
}

# Main script

main() {
    # Parse arguments
    while [[ $# -gt 0 ]]; do
        case $1 in
            -h|--help)
                usage
                ;;
            --output)
                OUTPUT_DIR="$2"
                shift 2
                ;;
            *)
                if [ -z "$PROJECT_PATH" ]; then
                    PROJECT_PATH="$1"
                else
                    print_error "Unknown option: $1"
                    usage
                fi
                shift
                ;;
        esac
    done

    # Default project path to current directory
    if [ -z "$PROJECT_PATH" ]; then
        PROJECT_PATH="."
    fi

    # Welcome message
    print_header "AI-Driven Project Analysis"
    echo ""

    # Run workflow
    check_dependencies
    validate_project_path
    setup_output_directory
    run_enumeration
    create_analysis_workspace
    show_summary

    exit 0
}

main "$@"
