#Requires -Version 5.1

<#
.SYNOPSIS
    Generate comprehensive DeepWiki documentation from codebase index

.DESCRIPTION
    Generates 4-tier documentation:
    - Tier 1: Overview (overview.md)
    - Tier 2: Functional Summary (functional-summary.md)
    - Tier 3: Architecture diagrams (architecture/*.md)
    - Tier 4: Detailed module docs (modules/*.md)

    Also generates API Reference and Data Models documentation.

.PARAMETER Tiers
    Comma-separated tier numbers to generate (default: "1,2,3,4")

.PARAMETER OutputDir
    Output directory (default: .deepwiki)

.EXAMPLE
    .\Generate-DeepWiki.ps1 -Tiers "1,2" -Verbose

.NOTES
    Exit codes:
      0 - Success
      1 - Index not found
      2 - Invalid arguments
#>

[CmdletBinding()]
param(
    [string]$Tiers = "1,2,3,4",
    [string]$OutputDir
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

# Helper functions
function Get-RepoRoot {
    try {
        $gitRoot = git rev-parse --show-toplevel 2>$null
        if ($gitRoot) { return $gitRoot -replace '/', '\' }
    } catch {}
    return (Get-Location).Path
}

try {
    $repoRoot = Get-RepoRoot
    $indexDir = Join-Path (Join-Path $repoRoot '.analysis') 'index'

    if (-not $OutputDir) {
        $OutputDir = Join-Path $repoRoot '.deepwiki'
    }

    # Check prerequisites
    if (-not (Test-Path $indexDir)) {
        Write-Error "Codebase index not found. Run /speckitsmart.index first."
        exit 1
    }

    $metadataPath = Join-Path $indexDir 'metadata.json'
    if (-not (Test-Path $metadataPath)) {
        Write-Error "Index metadata missing. Run /speckitsmart.index --full to rebuild."
        exit 1
    }

    # Create directories
    Write-Verbose "Creating output directory: $OutputDir"
    @('', 'architecture', 'modules', 'api-reference', 'data-models') | ForEach-Object {
        New-Item -ItemType Directory -Force -Path (Join-Path $OutputDir $_) | Out-Null
    }

    $currentDate = Get-Date -Format "yyyy-MM-dd"
    $projectName = Split-Path $repoRoot -Leaf

    # Load index data
    Write-Verbose "Loading index data..."
    $metadata = Get-Content (Join-Path $indexDir 'metadata.json') -Raw | ConvertFrom-Json
    $structure = Get-Content (Join-Path $indexDir 'structure.json') -Raw | ConvertFrom-Json
    $apiEndpoints = Get-Content (Join-Path $indexDir 'api-endpoints.json') -Raw | ConvertFrom-Json
    $externalApis = Get-Content (Join-Path $indexDir 'external-apis.json') -Raw | ConvertFrom-Json
    $dataModels = Get-Content (Join-Path $indexDir 'data-models.json') -Raw | ConvertFrom-Json
    $dependencies = Get-Content (Join-Path $indexDir 'dependencies.json') -Raw | ConvertFrom-Json

    # Statistics
    $stats = $metadata.statistics

    # Parse tiers
    $tierArray = $Tiers -split ',' | ForEach-Object { $_.Trim() }

    Write-Host "Generating DeepWiki documentation..."
    Write-Host "Output directory: $OutputDir"
    Write-Host "Tiers: $Tiers"
    Write-Host ""

    # Generate index.md
    @"
# $projectName Documentation

> Auto-generated by DeepWiki

## Contents

1. [Overview](overview.md) - Quick introduction and statistics
2. [Functional Summary](functional-summary.md) - System capabilities
3. [Architecture](architecture/README.md) - Design patterns and diagrams
4. [Modules](modules/README.md) - Detailed component docs
5. [API Reference](api-reference/README.md) - REST, GraphQL, WebSocket
6. [Data Models](data-models/README.md) - Schemas and entities

---
Generated: $currentDate
"@ | Out-File (Join-Path $OutputDir 'index.md') -Encoding UTF8

    # Tier 1: Overview
    if ('1' -in $tierArray) {
        Write-Verbose "Generating Tier 1: Overview..."
        @"
# $projectName - Codebase Overview

> Auto-generated documentation from codebase index
> Generated: $currentDate

## Quick Statistics

| Metric | Count |
|--------|-------|
| Files Indexed | $($stats.indexed_files) |
| Classes | $($stats.total_classes) |
| Functions | $($stats.total_functions) |
| Interfaces | $($stats.total_interfaces) |
| REST Endpoints | $($stats.total_rest_endpoints) |
| GraphQL Resolvers | $($stats.total_graphql_resolvers) |
| WebSocket Handlers | $($stats.total_websocket_handlers) |
| External APIs | $($stats.total_external_apis) |
| Environment Variables | $($stats.total_env_vars) |

---
*This documentation was auto-generated by DeepWiki from the codebase index.*
"@ | Out-File (Join-Path $OutputDir 'overview.md') -Encoding UTF8
    }

    # Tier 2: Functional Summary
    if ('2' -in $tierArray) {
        Write-Verbose "Generating Tier 2: Functional Summary..."
        $funcSummary = @"
# $projectName - Functional Summary

> High-level overview of system capabilities

## Classes

"@
        foreach ($class in $structure.classes) {
            $funcSummary += "- **$($class.name)** - $($class.file):$($class.line)`n"
        }

        $funcSummary += "`n## Functions`n`n"
        foreach ($func in $structure.functions) {
            $funcSummary += "- ``$($func.name)`` - $($func.file):$($func.line)`n"
        }

        $funcSummary += "`n## API Endpoints`n`n"
        foreach ($endpoint in $apiEndpoints.rest_endpoints) {
            $funcSummary += "- **$($endpoint.method)** ``$($endpoint.path)`` - $($endpoint.file):$($endpoint.line)`n"
        }

        $funcSummary | Out-File (Join-Path $OutputDir 'functional-summary.md') -Encoding UTF8
    }

    # Tier 3: Architecture
    if ('3' -in $tierArray) {
        Write-Verbose "Generating Tier 3: Architecture..."
        @"
# Architecture Overview

## Component Diagram

``````mermaid
graph TB
    subgraph "Application Layer"
        App["Application Components"]
    end
    subgraph "API Layer"
        REST["REST API ($($stats.total_rest_endpoints) endpoints)"]
    end
    subgraph "External"
        Ext["External Services ($($stats.total_external_apis))"]
    end
``````

## Architectural Patterns

Based on the codebase structure:

- REST API Architecture - $($stats.total_rest_endpoints) HTTP endpoints
- $($stats.total_classes) classes
- $($stats.total_functions) functions
"@ | Out-File (Join-Path $OutputDir 'architecture' 'README.md') -Encoding UTF8
    }

    # Tier 4: Modules
    if ('4' -in $tierArray) {
        Write-Verbose "Generating Tier 4: Module Documentation..."
        $modulesIndex = @"
# Module Documentation

## Classes

"@
        foreach ($class in $structure.classes) {
            $modulesIndex += "- [$($class.name)]($($class.name).md) - $($class.file):$($class.line)`n"

            # Individual class doc
            @"
# $($class.name)

## Location

- **File**: ``$($class.file)``
- **Line**: $($class.line)

---
*Generated by DeepWiki*
"@ | Out-File (Join-Path $OutputDir 'modules' "$($class.name).md") -Encoding UTF8
        }

        $modulesIndex | Out-File (Join-Path $OutputDir 'modules' 'README.md') -Encoding UTF8
    }

    # API Reference
    Write-Verbose "Generating API Reference..."
    $apiRef = @"
# API Reference

## REST Endpoints

| Method | Path | File | Line |
|--------|------|------|------|
"@
    foreach ($endpoint in $apiEndpoints.rest_endpoints) {
        $apiRef += "| $($endpoint.method) | ``$($endpoint.path)`` | $($endpoint.file) | $($endpoint.line) |`n"
    }
    $apiRef | Out-File (Join-Path $OutputDir 'api-reference' 'README.md') -Encoding UTF8

    # Data Models
    Write-Verbose "Generating Data Models Documentation..."
    $dataRef = @"
# Data Models

## Database Schemas

| Table | File | Line | Type |
|-------|------|------|------|
"@
    foreach ($schema in $dataModels.database_schemas) {
        $dataRef += "| $($schema.table) | $($schema.file) | $($schema.line) | $($schema.schema_type) |`n"
    }

    $dataRef += "`n## ORM Entities`n`n| Entity | Table | File | Line |`n|--------|-------|------|------|`n"
    foreach ($entity in $dataModels.orm_entities) {
        $dataRef += "| $($entity.entity) | $($entity.table) | $($entity.file) | $($entity.line) |`n"
    }
    $dataRef | Out-File (Join-Path $OutputDir 'data-models' 'README.md') -Encoding UTF8

    $fileCount = (Get-ChildItem $OutputDir -Recurse -Filter "*.md").Count

    Write-Host ""
    Write-Host "[OK] DeepWiki documentation generated successfully!" -ForegroundColor Green
    Write-Host "[OK] Location: $OutputDir" -ForegroundColor Green
    Write-Host "[OK] Files generated: $fileCount" -ForegroundColor Green
    Write-Host ""
    Write-Host "Next steps:"
    Write-Host "  - View documentation: open $OutputDir\index.md"
    Write-Host "  - Query codebase: /speckitsmart.ask `"your question`""

    exit 0
}
catch {
    Write-Error $_.Exception.Message
    exit 1
}
